---
title: "calibration-flows"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: optimization
  TARGETFUNCTION: minsquare
  CALIBRATIONTYPE: flows
# parameters for calibration
calibrationParameters:
  stepSizeInit: 10
  iterations: 5
  iterationsArmijo: 100
...
