---
title: "calibration-flows"
basedOn: "default.yaml"
# scope and resolution
granularity: lowGran
periods: [2000, 2005, 2010]
startyear: 2005
calibperiods: 2005
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
statusQuoPreference: 0
reportingTemplate: ignoreShell_onlyRes
ltEternalShare: 0.05
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: optimization
  TARGETFUNCTION: minsquare
  CALIBRATIONTYPE: flows
  # AGGREGATEDIM: vin
  FIXEDBUILDINGS: TRUE
# parameters for calibration
calibrationParameters:
  stepSizeInit: 10
  iterations: 5
  iterationsArmijo: 20
  sensitivityArmijo: 0.04
...
