---
title: "calibration-stocks"
basedOn: "default.yaml"
# scope and resolution
granularity: lowGran
periods: [2005, 2010, 2015]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
ltEternalShare: 0.05
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: optimization
  TARGETFUNCTION: minsquare
  CALIBRATIONTYPE: stocks
  AGGREGATEDIM: vin
  SEQUENTIALREN: TRUE
# parameters for calibration
calibrationParameters:
  stepSizeInit: 1
  iterations: 10
  iterationsArmijo: 20
  sensitivityArmijo: 0.04
...
