---
title: "calibration-flows"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
ltFactor: 1.5
ltEternalShare: 0.15
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: optimization
  TARGETFUNCTION: minsquare
  CALIBRATIONTYPE: flows
# parameters for calibration
calibrationParameters:
  stepSizeInit: 1
  iterations: 30
  iterationsArmijo: 20
  sensitivityArmijo: 0.04
...
